pkg/contextutil/BUILD.bazel, pkg/contextutil/poll.go, pkg/controller/BUILD.bazel, pkg/controller/controller.go, pkg/controller/initspec.go, pkg/etcd/BUILD.bazel, pkg/etcd/etcdserver.go, pkg/privateapi/BUILD.bazel, pkg/privateapi/peers.go, pkg/privateapi/server.go, test/integration/BUILD.bazel, test/integration/basic.go, test/integration/basic_test.go
A simple integration test that brings up a single node etcd cluster and
checks we can list members.
=> Create first test

.travis.yml, Makefile
Based on
https://github.com/pubref/rules_protobuf/blob/master/.travis.yml
=> Add travis CI buildfile

pkg/controller/controller.go
* Backup periodically even if we don't have a full cluster
* Backup before adding / removing members
=> Backup under more circumstances

pkg/controller/controller.go, pkg/controller/etcdclusterstate.go, pkg/etcd/etcdprocess.go, pkg/etcd/restore.go, pkg/etcdclient/interfaces.go, pkg/etcdclient/member.go, pkg/etcdclient/v2.go, pkg/etcdclient/v3.go, test/integration/harness/etcd.go, test/integration/harness/node.go
Otherwise etcd3 connections start consuming lots of CPU
=> Close etcd connections cleanly

Makefile, cmd/etcd-backup/BUILD.bazel, cmd/etcd-backup/main.go, images/BUILD, pkg/backupcontroller/BUILD.bazel, pkg/backupcontroller/cleanup.go, pkg/backupcontroller/controller.go, pkg/controller/controller.go, pkg/etcd/BUILD.bazel, pkg/etcd/backup.go, pkg/etcd/etcdprocess.go, pkg/etcd/etcdserver.go, pkg/etcd/restore.go, pkg/etcdclient/BUILD.bazel, pkg/etcdclient/interfaces.go, pkg/etcdclient/localnode.go, pkg/etcdclient/v2.go, pkg/etcdclient/v3.go, test/integration/etcdinstalled_test.go
Provides an adoption path, and likely useful even for people not using etcd-manager.
=> Build standalone etcd-backup tool

README.md, pkg/controller/etcdclusterstate.go
=> Cleanup String() on etcdClusterPeerInfo

pkg/backup/vfs.go
=> Better diagnostic message on listing backups

Makefile, images/BUILD, tools/bazel.rc, tools/get_workspace_status.sh
This should mean we don't need docker
=> Use bazel to push images

cmd/etcd-manager/main.go, pkg/privateapi/cluster.proto, pkg/privateapi/discovery/discovery.go, pkg/privateapi/peers.go, test/integration/harness/node.go
My sloppy naming introduced a bug in the tests
=> Cleanup addresses vs endpoints

Gopkg.lock, Gopkg.toml
This doesn't actually change anything we care about
=> Lock to a particular k8s version

cmd/etcd-manager-ctl/main.go, pkg/apis/etcd/etcdapi.proto, pkg/commands/store.go, pkg/commands/vfs.go, pkg/controller/commands.go, pkg/controller/controller.go, pkg/controller/upgrade.go, test/integration/harness/cluster.go
This should allow for better consistency, even on S3
=> Use files for cluster status & spec

pkg/commands/vfs.go
Should be more self-explanatory
=> Rename commands to control

WORKSPACE, images/BUILD, pkg/controller/controller.go
This likely isn't sustainable indefinitely, but unblocks us for now.
=> Add etcd 3.1.12 and 3.2.18

pkg/controller/controller.go, pkg/etcd/etcdserver.go
This should let us GC the old data in future, while keeping it around in
case of disaster
=> Move data directories when we shut down etcd

pkg/controller/controller.go
e.g. if our quorum size is 2, don't try to perform leader
operations unless we have 2 peers that believe we are the leader.
=> Be more conservative when performing operations

images/BUILD, pkg/apis/etcd/etcdapi.proto, pkg/controller/controller.go, pkg/etcd/etcdserver.go, pkg/etcd/tar.go, pkg/volumes/aws/discovery.go
=> Misc cleanups

cmd/etcd-manager/main.go, pkg/volumes/aws/discovery.go, pkg/volumes/aws/volumes.go, pkg/volumes/interfaces.go, pkg/volumes/mounter.go
We can extract the etcd name from a tagged volume, and the IP address of
the node
=> Extract more information from cloud provider

cmd/etcd-manager/main.go, pkg/etcd/etcdprocess.go, pkg/etcd/etcdserver.go, pkg/etcd/restore.go, test/integration/harness/node.go
etcd3.2 changed behaviour to disallow listening on a name.
=> Set listen urls to listen on an IP

.travis.yml, Gopkg.lock, Gopkg.toml, README.md, cmd/etcd-manager-ctl/main.go, test/integration/etcdinstalled_test.go, test/integration/resize_cluster_test.go, test/integration/upgradedowngrade_test.go
We're going to manage our dependencies more closely
=> Update etcd 3.2.12 => 3.2.18

cmd/etcd-backup-ctl/BUILD.bazel, cmd/etcd-backup-ctl/main.go
=> Add etcd-backup-ctl command

.travis.yml, BUILD, pkg/etcd/etcdprocess.go, test/integration/BUILD.bazel
We can remove the download from .travis.yml
=> bazel test now downloads etcd automatically

pkg/controller/controller.go
This ensures that the cluster starts consistently.  Older versions of
etcd have trouble forming an initial cluster if not all DNS names
resolve.
=> Broadcast the member map before starting a new cluster

cmd/etcd-manager/main.go, pkg/controller/controller.go, test/integration/harness/node.go
=> Make backup interval configurable

pkg/controller/controller.go
The glog formatting was just printing an address.
=> Better logging of restore backup command

dev/release.sh
Not ideal - ideally we would do this in the same bazel run, but we
don't really want to be encouraging latest anyway!
=> Encourage pushing latest docker tag

pkg/controller/controller.go
=> Automatically refresh control-store when we have to restore from backup

.travis.yml, WORKSPACE
Add the latest bazel (0.21) to the test grid
=> Test bazel 0.21 with travis

pkg/controller/controller.go, pkg/controller/newcluster.go, pkg/etcd/etcdserver.go, pkg/etcd/pki.go, pkg/locking/info.go, test/integration/harness/node.go
Nothing substantial, just a few disambiguations and level changes.
=> Misc logging improvements

pkg/controller/controller.go
Also means we put it into a helper function
=> Release leader lock when we shut down

pkg/privateapi/peers.go
When we see the endpoints for a peer change, we automatically close
GRPC connections to it.  This avoids some edge cases where otherwise
we keep trying to connect with the same set of IPs.
=> Close GRPC connections when we see the endpoints change

pkg/volumes/mounter.go
This fixes problems on GCE when a volume is already mounted, on COS.
=> Volumes: consider symlinks when checking if a volume is mounted

images/BUILD
Something changed with http_file, but this is cleaner anyway.
=> Build all container images with extracted files

pkg/etcdclient/v2.go
This was what was causing the concurrent map modifications
=> Don't copy http.Transport

pkg/controller/controller.go
We don't want to assume that the controller works for newer etcd versions.
=> Don't act as leader for unknown etcd version

test/integration/harness/node.go
The logic was too strict - it failed if we restarted etcd (as we do
when enabling TLS).
=> Tests: fix wait-for-ready logic

WORKSPACE, test/integration/BUILD.bazel
Includes some important crypto fixes
=> Build with go 1.11.6

pkg/volumes/mounter.go
We include /rootfs and symlink dereferencing.
This allows recognizing mounted devices on CentOS on GCE.
=> Detect more aliases for devices

pkg/hosts/hosts.go, pkg/hosts/hosts_test.go
* Recover from out-of-order guard lines
* Don't write file if it hasn't changed
* Tests
Thanks to @granular-ryanbonham for finding the issue!
=> More robust /etc/hosts handing

BUILD, WORKSPACE, images/BUILD, test/integration/BUILD.bazel, test/integration/clusterformation_test.go
etcd 3.3.10 is the etcd version recommended for 1.14
=> Support etcd 3.3.10

.travis.yml, WORKSPACE
=> Update bazel rules-go

pkg/volumes/openstack/volumes.go
=> Use disk by id for mounting devices in OpenStack

pkg/volumes/openstack/volumes.go
ref https://github.com/kopeio/etcd-manager/pull/253
cc @justinsb
=> fix issues in #253

pkg/volumes/BUILD.bazel, pkg/volumes/openstack/BUILD.bazel, pkg/volumes/openstack/volumes.go, pkg/volumes/retry.go
=> OpenStack: retry device path

cmd/etcd-manager/BUILD.bazel, cmd/etcd-manager/main.go, pkg/volumes/boot.go, pkg/volumes/external/BUILD.bazel, pkg/volumes/external/discovery.go, pkg/volumes/external/volumes.go, pkg/volumes/mounter.go
External mode should work on bare-metal; the idea is that we expect
some external coordinator or person to set up volumes on disk.
=> Initial experimental support for external mode

cmd/etcd-manager/main.go, pkg/volumes/external/discovery.go, pkg/volumes/external/volumes.go
We were confusing etcd and etcd-events, previously (in external mode)
=> external mode: better filtering of volumes

README.md, docs/walkthrough.md
=> Move walkthrough from main readme; various documentation updates

images/BUILD, test/integration/BUILD.bazel
I missed that this was missing before!
=> Add etcd 3.4.3 to tests

Makefile, cmd/etcd-manager-ctl/main.go, cmd/etcd-manager/tools.go, go.mod, go.sum, pkg/hostmount/nsenter.go, pkg/hosts/hosts.go, pkg/volumes/aws/volumes.go, pkg/volumes/gce/volumes.go, pkg/volumes/openstack/util.go, pkg/volumes/openstack/volumes.go
Introduce two makefile targets and start cleaning up problems.
=> staticcheck: introduce and fix a few packages

pkg/pki/certs.go
Not a perfect fix, if you don't restart things every now and then, they could still expire. But it's at least closer and means if you do restart things, it will fix itself.
=> Add a check to renew certificates on startup if they expire in 60 days or less

pkg/backup/vfs.go
Fixes #326 
Not tested, but seems straightforward enough.
=> Simplify downloading backups

docs/backupstructure.md, pkg/controller/controller.go, pkg/locking/lock_test.go, pkg/pki/certs.go
This will aid merging into etcdadm
=> Fix some typos picked up by verify-spelling

README.md, cmd/etcd-manager-ctl/main.go, docs/restore-troubleshooting.md
=> Fix some problems with trailing spaces

tools/deb-tools/main.go
=> Add boilerplate to tools/deb-tools/main.go

images/base/BUILD
=> Fix bazel formatting

BUILD, Makefile, WORKSPACE, tools/deb-tools/.gitignore, tools/deb-tools/WORKSPACE
=> Regenerate bazel in tools/deb-tools

dev/check-hashes.sh
This should pick up both old images and mismatched images.
=> Add script to verify image hashes

pkg/volumes/azure/client.go
Make them easier to read as suggested in
https://github.com/kopeio/etcd-manager/pull/378.
=> Rename fields in the azure client struct

pkg/volumes/azure/volumes.go
This is needed so we can merge upstream:
https://github.com/kubernetes-sigs/etcdadm/pull/182
=> Fix small typo in code comment
