kopeio/etcd-manager

- Makefile
- pkg/contextutil/poll.go
- pkg/controller/controller.go
- pkg/etcdclient/v2.go
- pkg/privateapi/peers.go
- pkg/privateapi/server.go
- test/integration/basic_test.go
We previously waited for all the nodes, but we can instead just wait for
enough nodes that the quorum is the same size.  This means we can start
with 2/3 nodes or 4/5 nodes.
This isn't safe in general, because etcd doesn't have a strong notion of
a quorum, configurable separately from the nodes themselves.
> Allow cluster to start if we have quorum

- cmd/etcd-manager/BUILD.bazel
- cmd/etcd-manager/main.go
- pkg/controller/BUILD.bazel
- pkg/controller/controller.go
- pkg/locking/BUILD.bazel
- pkg/locking/flock.go
- pkg/locking/fs.go
- pkg/locking/info.go
- pkg/locking/interfaces.go
- pkg/locking/lock_test.go
- test/integration/BUILD.bazel
- test/integration/clusterformation_test.go
- test/integration/harness/BUILD.bazel
- test/integration/harness/cluster.go
- test/integration/harness/node.go
If we have access to a shared filesystem (or another suitable shared
store), we can use that to enforce a leadership mutex.
> Experimental locking implementation

- pkg/controller/restore.go
- pkg/controller/upgrade.go
- pkg/etcd/etcdprocess.go
- pkg/etcdclient/v3.go
This avoids us getting into a situation where we have to wait until
we're down to a single node to be sure that we get a backup with the
latest changes.
> Cleaner upgrade: quarantine nodes, then do a backup

- pkg/etcd/etcdprocess.go
It just causes confusion to have a second API serving from a different
datastore.
> Disable etcd2 endpoint for etcd3

- pkg/etcd/etcdserver.go
When the cluster is created/joined, we should exit the prepared state.
> etcdserver should exit prepared state

- test/integration/clusterformation_test.go
- test/integration/harness/cluster.go
- test/integration/harness/etcd.go
- test/integration/harness/node.go
- test/integration/upgradedowngrade_test.go
Most importantly, waiting for cluster ready before proceeding, not just
for the member list to be returned.
> More test cleanups / fixes

- Makefile
Runs `dep ensure` and then regenerates bazel BUILD files.
> makefile: add dep-ensure target

- .gitignore
- dev/add-symlink.sh
These symlinks help IDEs see the generated protobuf code
> Add symlink script

- test/integration/datapersists_test.go
Local reads aren't guaranteed until a quorum read has succeeded
> Fix race in test

- cmd/etcd-manager-ctl/main.go
- pkg/apis/etcd/etcdapi.proto
- pkg/backup/fs.go
- pkg/backup/store.go
- pkg/backup/vfs.go
- pkg/controller/BUILD.bazel
- pkg/controller/commands.go
- pkg/controller/controller.go
- pkg/controller/restore.go
- pkg/controller/upgrade.go
- pkg/etcd/etcdserver.go
- test/integration/harness/cluster.go
We run all changes through the etcd spec, and avoid making any dangerous
changes without an explicit command.  The commands are stored in a queue
on VFS (in the backup store).
> Stricter model for changes

- WORKSPACE
Otherwise we are implicitly going by the bazel rules version
> Explicitly specify go version to use

- test/integration/harness/etcd.go
- test/integration/harness/node.go
Should be a no-op refactor, and sets us up to enable TLS.
> Refactor test to create etcdclient consistently

- pkg/etcd/pki.go
This way we can still query it locally.
> Always add 127.0.0.1 to certificate SANs

- WORKSPACE
We were seeing some concurrent map writes under the stress-test
otherwise, in the http stack it looked like.
> Use go 1.11.4

- cmd/etcd-manager/main.go
We had to introduce this for breaking changes in etcd, but it also
breaks our walkthrough.
> Make ListenAddress configurable

- WORKSPACE
- images/BUILD
This means we know what we're getting, that we can support multiple
architectures, but also that we pick up some critical bug fixes -
particularly around caching of /etc/hosts
> Build etcd2 from source

- pkg/controller/controller.go
etcdclient still hangs on ListMembers calls, so we set a relatively
short timeout in our controller.
> Short timeout for etcd ListMembers

- pkg/privateapi/peers.go
Our gossip network is assumed to be reasonably low latency (it has to
support etcd!), so we reduce the maximum backoff for GRPC.
> GRPC: limit backoff in gossip communications

- test/integration/clusterformation_test.go
- test/integration/harness/etcd.go
Switch to Fatalf instead of Errors when we have to immediately stop
the test.
> Integration tests: fix a few error paths to avoid panics on errors

- pkg/controller/controller.go
- pkg/controller/etcdclusterstate.go
- pkg/etcd/etcdserver.go
- pkg/etcdclient/member.go
ClientURLs can be controlled by etcd command line flags, and when that
happens the member information stored in etcd might be out of date.
So we have to be much more careful in building the list of client
urls.
> Allow for incorrect ClientURLs

- pkg/privateapi/id.go
Mostly fixes some edge cases in the tests
> Add missing mkdir when generating a node id

- pkg/etcd/etcdprocess.go
Build it in the keystore the client provides.
> BuildTLSKeypairs: don't force an ephemeral key

- pkg/controller/controller.go
- pkg/controller/upgrade.go
If we end up in a state where some nodes are quarantined but others
are not, move to a state where all are quarantined.
This should allow us to recover from a state where we failed to lift
or raise the quarantine.
> Ensure cluster is consistently quarantined

- pkg/etcdclient/v3.go
The shorter timeouts help us detect failed etcd nodes faster.
> etcd3 client - use much shorter timeouts

- test/integration/harness/node.go
> tests: return error instead of panic-ing

- pkg/backupcontroller/controller.go
- pkg/etcd/backup.go
- test/integration/harness/etcd.go
- test/integration/harness/node.go
- test/integration/upgradedowngrade_test.go
Added a few places where I forgot this - mostly tests, but also some backup code paths.
> Don't forget to call client.Close()

- dev/release.sh
We sync up with the etcd release version to avoid confusion.
> Mark release v3

- cmd/etcd-backup/main.go
- images/BUILD
- pkg/backupcontroller/controller.go
- pkg/etcdclient/interfaces.go
The following flags are made available for etcd-backup:
```
client-ca-file: Path to a CA cert file to validate the Server Certificate
client-cert-file: Path to the etcd client TLS Certificate file
client-key-file: Path to the etcd client TLS Certificate Key file
```
Fixes #189
> Support TLS for etcd backups

- dev/release.sh
So that it's clear which source release corresponds to a particular tag.
> Update release script to push tags

- pkg/legacy/adopt.go
Keeping it simple (at the expense of elegance) in the interest of
reliability.
> Recognize https urls when adopting

- cmd/etcd-manager-ctl/main.go
Improve help output of etcd-manager-ctl to show proper arg command position and show list of available commands.
> Improve etcd-manager-ctl cmd help output.

- pkg/hosts/hosts.go
When we have multiple writers racing to write /etc/hosts, we could
have file corruption where we see a mix of both files.
We can't use a traditional atomic file write, because we are
bind-mounting /etc/hosts.
Instead we write to /etc/hosts, pause, then re-read the contents.  If
the contents don't match, we repeat.  This will not result in fair
queuing, but will avoid corruption.
> Avoid concurrent write corruption to /etc/hosts

- pkg/etcd/restore.go
We don't ship every version of etcd; but we can usually use a version
with the same major/minor to restore.  We start a "safelist" for using
one of the versions we do ship to restore a backup, restoring 3.1.11
with 3.1.12.
Issue https://github.com/kubernetes/kops/issues/6990
> Support restoring from compatible minor version

- BUILD
- WORKSPACE
- images/BUILD
- test/integration/BUILD.bazel
- test/integration/clusterformation_test.go
Potential fix for https://github.com/kubernetes/kops/issues/6875.
Fix potential grpc leak:
https://github.com/etcd-io/etcd/blob/master/CHANGELOG-3.3.md#v3311-2019-1-11
Test seems to be timing out due to length
> Add etcd 3.3.13

- WORKSPACE
- images/BUILD
We switch to distroless static, as the images that were using
hyperkube have switched to that.
> Update base image

- cmd/etcd-manager/main.go
- pkg/etcd/etcdprocess.go
- pkg/etcd/etcdserver.go
- test/integration/harness/node.go
We map it through from the command line, and by passing it with an
env-var we can pass it to older versions (that will ignore it)
> Support listen-metrics-urls option

- pkg/legacy/adopt.go
I tried to use etcd-manager in kops which is setup to use a proxy to pull docker images.
```
spec:
assets:
containerProxy: nexus.internal:8500
```
But starting etcd-manager would always abort with `error initializing etcd server: unexpected etcd image \“nexus.internal:8500/etcd:2.2.1\“`
The two colons do incorrectly let a check fail to verify the specified name of the etcd docker image.
> Fix unexpected etcd image error if docker pulls images over proxy

- images/BUILD
- test/integration/BUILD.bazel
Add etcd-manager-ctl and etcd-backup-ctl to their respective images.
This will make it easier to for users to get a hold of the binaries where they are needed.
> Add etcd-manager-ctl and etcd-backup-ctl to their respective images.

- WORKSPACE
- images/BUILD
Also put some symlinks in the more logical location, as the debug image puts the symlinks into /busybox
> Use debug distroless image, so we have shell & tar

- .gitignore
- dev/build-assets.sh
- dev/release.sh
Engineers may require `etcd-manager-ctl` to manage backups (ie. issue a restore command). Contrary to `etcd-manager` which gets shipped in a Docker image, `etcd-manager-ctl` is not strictly required to run in the same container while it can be run on any system having access to the remote storage (ie. engineer's workstation with privileges to read/write the related S3 bucket).
In this PR I'm proposing to release `etcd-manager-ctl` binaries via GitHub release's assets. I haven't found any automatism to create the GitHub release, so I've assumed it's created manually at this stage.
Fixes https://github.com/kopeio/etcd-manager/issues/201.
> Added instructions and script to release etcd-manager-ctl binaries

- WORKSPACE
- images/BUILD
We need e2fs utilities and nsenter to mount disks.
Update the base image though!
> Revert base image back to (latest) debian-hyperkube-base

- docs/backup-restore.md
In an effort to better understand how `etcd-manager` works under the hood, in order to be able to intervene in case of production issues on our Kubernetes clusters, I've attempted a documentation of how backup restore works.
I've extracted it reading the code and comparing it with `etcd-manager` logs during a backup restore procedure. I'm not sure it's everything correct and I would be glad if you could help me fix everything which may be inaccurate.
> Documented how backup restore works under the hood

- WORKSPACE
The older version we were previously using is incompatible with bazel 1.0
> Update rules-docker to 0.12

- cmd/etcd-manager/main.go
- pkg/volumes/do/discovery.go
- pkg/volumes/do/volumes.go
This PR is related to the PR that's merged in KOPS (https://github.com/kubernetes/kops/pull/7566)
As part of this change, we have consistent volume tags and droplet tags that are used when bringing up the DO cluster. These tags are matched and accordingly the volumes and associated to the correct droplets.  This change should help in associating multi master nodes, previously DO only supported a single node master.
Once this change is merged, will update KOPS with the newer version of etcd-manager. Also will be sending another PR on KOPS side for protokube seed cluster changes.
> [DO-7442] Fix logic for Digital Ocean volume tag

- WORKSPACE
We want to pick up a few security fixes.
> Update golang to 1.13.3

- .travis.yml
Some of these bazel versions were effectively obsolete; move testing
to the versions in more widespread use.
> travis: Test newer bazel versions

- pkg/hosts/hosts_test.go
Looks like the golden output was simply not correct in a few places.
> Fix unit tests

- .travis.yml
- Makefile
Otherwise we were skipping the hosts unit tests.
> Test everything, not just //test

- cmd/etcd-manager/main.go
etcd-manager added support for --listen-metric-urls as a pass-through argument for etcd, however there seems to be a typo - while the etcd argument uses listen-metric**s**-urls, etcd-manager's is missing an s.
> rename etcd-manager argument listen-metrics-url to match etcd's

- Makefile
- WORKSPACE
- vendor/google.golang.org/grpc/internal/channelz/BUILD.bazel
- vendor/google.golang.org/grpc/internal/syscall/BUILD.bazel
- vendor/k8s.io/kubernetes/pkg/util/mount/BUILD.bazel
- vendor/k8s.io/kubernetes/pkg/util/nsenter/BUILD.bazel
Move to go 1.13.4, which has a http2 fix; we haven't seen it but it
seems worth picking up given our use of GRPC.
> Update bazel rules

- pkg/etcdclient/v2.go
Picked up by `go vet` / `nogo`
> Remove duplicate error handling

- pkg/volumes/aws/volumes.go
- pkg/volumes/do/volumes.go
- pkg/volumes/gce/volumes.go
- pkg/volumes/openstack/volumes.go
- pkg/volumes/retry.go
This helps the retry logic work correctly.
> Ensure that FindMountedVolume returns ("", nil) when not found

- pkg/etcdclient/localnode.go
We weren't correctly trying all endpoints; as detetced by staticcheck.
Not terribly likely to happen in practice, but not what was intended.
> Fix error handling bug

- BUILD
- WORKSPACE
- images/BUILD
- pkg/etcdversions/mappings.go
- test/integration/BUILD.bazel
Addresses #249 by adding etcd 3.4.3 for kubernetes version 1.17
Signed-off-by: mmerrill3 <michael.merrill@vonage.com>
> Adding etcd 3.4.3 into the layers for etcd-manager

- docs/restore-troubleshooting.md
Added troubleshooting information for slow api server and old master leases after discussion in kubernetes/kops#7054.
I'll add a link to this doc from the kops docs after this is merged.
> Add troubleshooting info for restoring cluster

- Makefile
It's much more description of the intent, not the mechanism.
> Makefile: rename dep-ensure target to vendor

- pkg/etcd/etcdprocess.go
This allows a user to overwrite etcd setting with env vars.
There's no validation done to the user set overwrites.
> Allow overwriting etcd configs with env variables.

- BUILD
- WORKSPACE
- images/BUILD
- pkg/etcdversions/mappings.go
- test/integration/BUILD.bazel
This is used by K8s 1.16: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.16.md#changed
Note: I'm having bazel issues running `make test` on the master branch so I haven't had a chance to confirm the tests pass with this PR.
> Add support for etcd 3.3.17

- pkg/etcd/pki.go
PR to address issue (#305 )
Signed-off-by: mmerrill3 <michael.merrill@vonage.com>
> Adding client usage extension for server cert (#305)

- pkg/locking/BUILD.bazel
I forgot to regenerate bazel last time (and bizarrely, the tests still
passed)
> Bazel: update dependency

- pkg/etcdclient/interfaces.go
- pkg/etcdclient/v2.go
- pkg/etcdclient/v3.go
- test/integration/harness/cluster.go
- test/integration/harness/node.go
- test/integration/upgradedowngrade_test.go
Particularly with etcd2, we're seeing some flakes when run in github
actions (which I assume is generally less powerful than some of the
other configurations).
The most recent error was the node not having a leader, so (briefly)
wait for that along with node health before starting the test.
> e2e tests should wait for cluster readiness

- .travis.yml
Old bazel v1 versions are no longer compatible with latest rules-go.
Also update bazel v2 tests to test with our preferred version (2.2.0)
> Remove old bazel versions from travis

- pkg/pki/BUILD.bazel
- pkg/pki/certs.go
- pkg/pki/certutils.go
- pkg/pki/parse_test.go
- test/integration/upgradedowngrade_test.go
We raise the minimum required time to 20 years, effectively ensuring
that we won't reuse certificates.
We also now issue them for 2 years, to allow for the longer time
horizons of LTS kubernetes support.
Both these values can be customized through env vars, the defaults
correspond to these env vars:
ETCD_MANAGER_CERT_DURATION=2y
ETCD_MANAGER_CERT_MIN_TIME_LEFT=20y
> Always renew certificates

- pkg/backupcontroller/cleanup.go
At the moment backup retention is hardcoded.
Hourly backups are kept for 7 days and daily backups are kept for 1 year.
Env vars could be used to customise backup retention:
```
ETCD_MANAGER_HOURLY_BACKUPS_RETENTION=7d
ETCD_MANAGER_DAILY_BACKUPS_RETENTION=1y
```
Fixes #225 
Fixes #308
> Use env vars to customize backup retention

- pkg/volumes/aws/BUILD.bazel
- pkg/volumes/aws/volumes.go
Trying to attach volumes with same device names adds unnecessary delays.
With this fix, kube-apiserver starts in less than a minute after NodeUp finishes.
Fixes #217
> Use next attachment point when device already in use

- pkg/backup/vfs.go
Remove the dependency on `vfs.CopyFile()`, which internally copies to a second temporary file.
> Simplify uploading backups

- pkg/volumes/openstack/config.go
- pkg/volumes/openstack/volumes.go
Application credentials allows you to export a purpose-specific set of
credentials for a user instead of exposing user login credentials.
Especially useful when using LDAP or similar for Openstack users.
Also lets you rotate credentials more easily since multiple application
credentials can be provisioned per user.
> Adds support for using OS application credentials

- vendor/k8s.io/kops/util/pkg/vfs/swiftfs.go
OpenStack features expiring tokens which requires a client to reauth.
This fix ensures etcd-manager can continue creating backups to Swift
when the token expiry time is hit.
Fixes https://github.com/kubernetes/kops/issues/9730
> Fixes usage of OpenStack Swift reauthentication

- WORKSPACE
- images/BUILD
Given the latest debian-hyperkube-base is based on Debian Stretch which is no longer receiving security updates as of 07/06/2020 and that k/k has completely stopped using it (kubernetes/kubernetes#88676) we should migrate off it as well.
> Move from debian-hyperkube-base to debian-base

- BUILD
- WORKSPACE
- images/BUILD
- pkg/etcdversions/mappings.go
- test/integration/BUILD.bazel
xRef: https://github.com/kubernetes/kubernetes/pull/94536
CC: @justinsb @rifelpet
> Add support for etcd 3.4.13

- WORKSPACE
- images/BUILD
Switch to using  gcr.io/cloud-marketplace-containers/google/debian10 as there is an issue installing additional packages with install_pkgs onto image k8s.gcr.io/build-image/debian-base-amd64. Testing installation with other base Debian images work with no issues, however I have not been able to isolate the issue with utilizing k8s.gcr.io/build-image/debian-base-amd64
l.gcr.io/google/debian10 already contains the required packages so no need to install anything.
Fixes an issue introduced in #340
> Switch to gcr.io/cloud-marketplace-containers/google/debian10 - Fix for #340 option 1

- BUILD
- Makefile
- WORKSPACE
- images/BUILD
- images/etcd.bzl
- test/integration/BUILD.bazel
Taking #315 a bit further.
The manifest part can be done in 2 ways separately:
1. Using `docker manifest ...`:
```bash
$ export DOCKER_CLI_EXPERIMENTAL=enabled
$ docker manifest create \
kopeio/etcd-manager:docker \
kopeio/etcd-manager-amd64:latest kopeio/etcd-manager-arm64:latest
$ docker manifest push --purge kopeio/etcd-manager:docker
```
2. Using `manifest-tool ...`:
```bash
$ manifest-tool push from-args \
--platforms linux/amd64,linux/arm64 \
--template kopeio/etcd-manager-ARCHVARIANT:latest \
--target kopeio/etcd-manager:latest
```
> Support for ARM64

- pkg/volumes/openstack/discovery.go
- pkg/volumes/openstack/volumes.go
BUG:
If we have openstack region which do have multiple AZs in computes AND volumes, this whole discovery mechanism does not work at all (similar setup that AWS region has). When doing discovery it should ignore the AZ, no matter what - when mounting volumes it should instead use zones
@justinsb could you check this
> BUG: OpenStack ignore AvailabilityZone in discovery

- cmd/etcd-manager-ctl/main.go
- docs/restore-troubleshooting.md
This commit refactors the `runDeleteCommand` function of
`etcd-manager-ctl` to use the "backup name" instead of the "timestamp"
attribute. More often than not, users are more likely to become familiar
with the syntax of `etcd-manager-ctl restore-backup`, which uses the
`backupname` attribute to identify the target backup to restore.
By bringing the `delete-backup` subcommand in alignment with
`restore-backup`, we improve the user experience of an operator in the
process of restoring a cluster.
> feat(etcd-manager-ctl): use backupname to delete backup instead of timestamp

- cloudbuild.yaml
The older image is deprecated and no longer guaranteed to contain any
particular bazel version.
> Switch the cloudbuild docker image, locking to 2.2.0

- WORKSPACE
Due to https://github.com/bazelbuild/rules_go/issues/456 , the build of etcd 2.2.1 did not work correctly on case-insensitive file systems, including MacOS.
etcd has a shell script named `build`, which bazel was treating as a `BUILD` file.  By setting bazel to only look for `BUILD.bazel` files, this is avoided.
> Fix build on case-insensitive file systems (MacOS)

- pkg/etcd/pki.go
- pkg/tlsconfig/options.go
This should address the deprecation in go 1.15 of server certificates that only have a Common Name (CN).
> Set AltNames on server certificates

- pkg/volumes/external/volumes.go
Simple fix while I was seeing if the bazel vet support works yet (it doesn't, but it might when we update rules-go)
> govet: Fix a log message

- BUILD
- WORKSPACE
It has its own (separate) bazel configuration
> Exclude gazelle from tools/deb-tools

- WORKSPACE
This was causing the arm64 image to not work.
> Fix some incorrect base image hashes for arm64

- test/integration/harness/cluster.go
- test/integration/harness/etcd.go
- test/integration/harness/node.go
- test/integration/secure_transitions_test.go
This should make diagnostics of failed tests a little easier.
> Add more descriptions to wait loops

- pkg/controller/controller.go
- pkg/etcd/pki.go
Signed-off-by: mmerrill3 <michael.merrill@vonage.com>
- Wrapping new etcd client member listings around an explicit timeout #371 
- localhost loopback IP only needs to be in IP list of SAN certificate once
> Handling hanging list command from etcd client during reconciliation loop

- cmd/etcd-manager/main.go
- pkg/etcd/etcdserver.go
- pkg/etcd/pki.go
- pkg/etcd/restore.go
- test/integration/harness/node.go
This addresses the deeper client-certificate validation introduced in
etcd 3.2, without relying on DNS.
> Include IPs in peer certificates

- test/integration/clusterformation_test.go
- test/integration/datapersists_test.go
- test/integration/harness/cluster.go
May be a good idea to move to a newer version of etcd in tests, where possible.
> Use etcd v3.4.13 in tests

- pkg/controller/controller.go
- pkg/privateapi/leadership.go
- pkg/privateapi/peers.go
Previously we assumed that if our peers didn't change and we had the
leadership, that the peers would continue to acknowledge our
leadership.  But this assumes that a peer didn't restart or crash.
Instead, on every leader iteration, check with all the peers that we
are still the leader (using the same GRPC method).  For negligible
additional traffic, this should enable greater recovery from errors
and greater consistency of leader election.
Issue #348
> Eager-broadcast leadership on every leader iteration

- cmd/etcd-manager/main.go
- pkg/privateapi/peers.go
- pkg/privateapi/server.go
- test/integration/harness/node.go
current solution is that it will query discovery `Poll` each minute. However, when we have for instance kops cluster it means that we have 6 etcd manager processes. This means that etcd-manager will query each 10 seconds the status from the cloudprovider API. This means total 8640 queries/day and in case of for instance OpenStack / GCP it makes also 8640 * 3 ~ 26k compute API calls /day. In my opinion this is too much and that is why I would like to configure this value.
It is not problem if we have one cluster in whole cloud, but if we have for instance 100 kops clusters those numbers are pretty high.
> Make discovery poll interval configurable

- pkg/controller/controller.go
- pkg/etcd/etcdserver.go
- pkg/hosts/hosts.go
- pkg/privateapi/leadership.go
This PR would change Etcd-manager to use klog.V(3).Infof instead of plain klog.Infof for frequently occuring informational events.
We have been looking into logs generated by etcd-manager. Running an idle cluster with three master nodes, i.e. two etcd-manager clusters and six members with -v=1 results in about 300 000 log events in 24h, without significant deviations after running for few days.
After these changes, the number of log events is somewhere around 2000 events per day, which mostly include information about backup and compaction events.
> Add log levels to prevent too verbose logging

- dev/build-assets.sh
The output paths of bazel binaries has moved.  kOps has a different
workaround, where the output paths are selected based on platform; we
could look at that instead in future.
> scripts: Find bazel output in the new locations
